version: '3.4'

services:
  backend:
    build:
      context: .
    image: back_dev
    volumes:
      - ./media:/app/media:rw
    container_name: back_dev
    ports:
      - "8000:8000"
    restart: "unless-stopped"

  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=zYv280IeT45^
    container_name: pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  pgdbdata: null
