version: '3.4'

services:
  backend:
    build:
      context: .
    image: back_dev
    container_name: back_dev
    ports:
      - "8000:8000"
    restart: "unless-stopped"

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=bronkz
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=bronkzdb

volumes:
  postgres_data: