# Generated by Django 4.2.3 on 2023-07-11 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='request',
            unique_together={('date', 'time')},
        ),
    ]
