# Generated by Django 4.2.3 on 2023-07-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_request_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtype',
            name='coast',
            field=models.IntegerField(default=12000),
            preserve_default=False,
        ),
    ]
