# Generated by Django 4.2.3 on 2023-07-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_fieldtype_coast'),
    ]

    operations = [
        migrations.AddField(
            model_name='defuser',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
