# Generated by Django 4.2.3 on 2023-07-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_defuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='defuser',
            name='photo',
            field=models.ImageField(blank=True, upload_to='user_photo'),
        ),
    ]
