# Generated by Django 4.2.3 on 2023-08-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_defuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtype',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldtype',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
