# Generated by Django 4.2.3 on 2023-08-06 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_fieldtype_lat_fieldtype_lng'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='request',
            unique_together=set(),
        ),
    ]
