# Generated by Django 4.2.3 on 2023-08-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_request_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='book',
            field=models.BooleanField(default=False),
        ),
    ]
