# Generated by Django 4.2.3 on 2023-09-04 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_request_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='defuser',
            name='fcmToken',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='FcmToken'),
        ),
        migrations.AddField(
            model_name='field',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
