# Generated by Django 4.2.3 on 2023-09-10 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_defuser_fcmtoken_field_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='cancel_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PermanentBookedRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fieldtype')),
            ],
        ),
    ]
