# Generated by Django 4.2.3 on 2023-09-15 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_request_cancel_time_permanentbookedrequests'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='field_photo')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.field')),
            ],
        ),
    ]
